### ISSUE TITLE
FIRInvalidArgumentExceptionでアプリがクラッシュする

### ISSUE THREAD

**Issue by yuuki00682200** [kojake/N-Friends#10]

**Comment by yuuki00682200** [comment]
エラー読むと以下がわかる
LikedMatchedViewクラスのFetchMatchUsername_Image or FetchMatchUserの処理中にクラッシュしている。

documentWithPathに対して値を渡すとき、空っぽではないことを確認する

**Comment by yuuki00682200** [comment]
どの条件下で発生するのかアプリQAを実施したい

**Comment by Kaito1108** [comment]
okです。
調査してみます

**Comment by Kaito1108** [comment]
一応、自分今まではLikedMatchedViewでのクラッシュは確認できていません。

**Comment by yuuki00682200** [comment]
画面下部のTabをスワイプのカードが表示される前に動きまくるとクラッシュするっぽいですね

**Comment by Kaito1108** [comment]
めっちゃ動かしてみましたけど全くクラッシュしませんでした。


https://github.com/kojake/N-Friends/assets/120543115/2b008759-4524-47ec-9787-af6f4d45ed17

**Comment by yuuki00682200** [comment]
https://github.com/kojake/N-Friends/assets/46854753/78224d32-1039-4e5b-b2a6-38a10892ec5b

**Comment by yuuki00682200** [comment]
どうだろう？

**Comment by Kaito1108** [comment]
ちょっと自分の方では実機&シュミレーターで検証してもクラッシュしませんでした。

**Comment by yuuki00682200** [comment]
うーんなんでなんだろうか。UID依存な気もする。新しくアカウント作って再現するかどうか確認してみてほしいです！

**Comment by Kaito1108** [comment]
了解です!

**Comment by Kaito1108** [comment]
ちょっとマジで原因がわからないので一回高津さんの実機の方で試してみてください

**Comment by yuuki00682200** [comment]
うーん治らないか、、🤔🤔

**Comment by Kaito1108** [comment]
マジで何にも言わないんでわからんないんすよね...
シュミレーターで動かしても変わんないので...🤦

**Comment by yuuki00682200** [comment]
メールに実機動画送りました

**Comment by yuuki00682200** [comment]
なんかログアウト関係もおかしそう。アカウントがおかしいのかと思って切り替えたらログイン保持の影響受けてて謎動作してます

**Comment by Kaito1108** [comment]
ちょっとまた調査してみます

**Comment by Kaito1108** [comment]
すいません
多分UID関係なんじゃないかなと予想しているんですが、なんせこっちでクラッシュしてないので
今週の土曜に修正する感じで回していいですか？

**Comment by yuuki00682200** [comment]
もちろんそれでOK！おそらく自分のUIDが死んでる可能性はありなので、firebaseでアカウント消して再度やってみますね

**Comment by yuuki00682200** [comment]
@kojake 
Firebaseでアカウント削除したら改善しました。
やはりUIDで何かあったっぽい

**Comment by yuuki00682200** [comment]
他何か解決できていないissueあれば立ててくださいー！

**Comment by Kaito1108** [comment]
ログインの時とかにUID上手く取得できてなかったんですかね

**Comment by yuuki00682200** [comment]
このissueはcloseでOK
