### ISSUE TITLE
アカウント削除時のバグ

### ISSUE THREAD

**Issue by Kaito1108** [kojake/N-Friends#9]
# 発生していること
アカウント削除時にエラーが発生している

# 原因
ログインの履歴が残っていたらアプリ起動時にログインするのだがそれをすると
あんまりよくわからんけどログインしたことになってない
ので、削除の際にエラーが発生している。

現在対応中

**Comment by kojake** [comment]
2f8a3a1832db016a476a40e0631647d776b0e16eでバグ修正完了

**Comment by Kaito1108** [comment]
2f8a3a1832db016a476a40e0631647d776b0e16e でバグ修正完了
